### PR TITLE
Add golang book (Dasar Pemrograman Golang)

### PR DESCRIPTION
**Pull request by afadhitya**

### CODE REVIEW

**Comment by fransallen** [comment]
Please see [CONTRIBUTING.md](https://github.com/fransallen/awesome.id/blob/main/CONTRIBUTING.md).

**Comment by fransallen** [comment]
At the end of the description, `Dasar` is it supposed to be lowercase? We want to build good and interesting descriptions :)

**Comment by afadhitya** [comment]
Okay sorry for that. Is there anything that I need to change besides that?

**Comment by fransallen** [comment]
Cool, this should be good now. Thank you!

**Pull request merged**
